Edición del archivo README.md
Marianod2003/Proyectogrupo21 pull request #29
Opened 2023-10-13 17:54 UTC by mumido

Se modifica y agrega información al archivo readme

2023-10-13 17:57 UTC, Anibal-GitHub approved these changes

2023-10-13 18:27 UTC, licette32 approved these changes

2023-10-15 21:13 UTC, Marianod2003 requested changes
Cambiar a la rama de desarrollo develop

2023-10-15 21:17 UTC, closed without merging

2023-10-15 21:17 UTC, Marianod2003 commented
Pasar a rama de producción